package gov.shenyang.zwfw.mapper;

import gov.shenyang.zwfw.model.TreatmentRecord;
import gov.shenyang.zwfw.model.TreatmentRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface TreatmentRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_record
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    long countByExample(TreatmentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_record
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    int deleteByExample(TreatmentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_record
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_record
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    int insert(TreatmentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_record
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    int insertSelective(TreatmentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_record
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    List<TreatmentRecord> selectByExampleWithRowbounds(TreatmentRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_record
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    List<TreatmentRecord> selectByExample(TreatmentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_record
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    TreatmentRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_record
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") TreatmentRecord record, @Param("example") TreatmentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_record
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    int updateByExample(@Param("record") TreatmentRecord record, @Param("example") TreatmentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_record
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    int updateByPrimaryKeySelective(TreatmentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_record
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    int updateByPrimaryKey(TreatmentRecord record);
}
