package gov.shenyang.zwfw.model;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_id
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    private Long adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_name
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_email
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    private String adminEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_tel
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    private String adminTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.token
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_id
     *
     * @return the value of admin.admin_id
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_id
     *
     * @param adminId the value for admin.admin_id
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_name
     *
     * @return the value of admin.admin_name
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_name
     *
     * @param adminName the value for admin.admin_name
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_email
     *
     * @return the value of admin.admin_email
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public String getAdminEmail() {
        return adminEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_email
     *
     * @param adminEmail the value for admin.admin_email
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail == null ? null : adminEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_tel
     *
     * @return the value of admin.admin_tel
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public String getAdminTel() {
        return adminTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_tel
     *
     * @param adminTel the value for admin.admin_tel
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public void setAdminTel(String adminTel) {
        this.adminTel = adminTel == null ? null : adminTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.token
     *
     * @return the value of admin.token
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.token
     *
     * @param token the value for admin.token
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }
}