package gov.shenyang.zwfw.model;

import java.util.ArrayList;
import java.util.List;

public class ApplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table apply
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table apply
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table apply
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public ApplyExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table apply
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andIdCardPicIsNull() {
            addCriterion("id_card_pic is null");
            return (Criteria) this;
        }

        public Criteria andIdCardPicIsNotNull() {
            addCriterion("id_card_pic is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardPicEqualTo(String value) {
            addCriterion("id_card_pic =", value, "idCardPic");
            return (Criteria) this;
        }

        public Criteria andIdCardPicNotEqualTo(String value) {
            addCriterion("id_card_pic <>", value, "idCardPic");
            return (Criteria) this;
        }

        public Criteria andIdCardPicGreaterThan(String value) {
            addCriterion("id_card_pic >", value, "idCardPic");
            return (Criteria) this;
        }

        public Criteria andIdCardPicGreaterThanOrEqualTo(String value) {
            addCriterion("id_card_pic >=", value, "idCardPic");
            return (Criteria) this;
        }

        public Criteria andIdCardPicLessThan(String value) {
            addCriterion("id_card_pic <", value, "idCardPic");
            return (Criteria) this;
        }

        public Criteria andIdCardPicLessThanOrEqualTo(String value) {
            addCriterion("id_card_pic <=", value, "idCardPic");
            return (Criteria) this;
        }

        public Criteria andIdCardPicLike(String value) {
            addCriterion("id_card_pic like", value, "idCardPic");
            return (Criteria) this;
        }

        public Criteria andIdCardPicNotLike(String value) {
            addCriterion("id_card_pic not like", value, "idCardPic");
            return (Criteria) this;
        }

        public Criteria andIdCardPicIn(List<String> values) {
            addCriterion("id_card_pic in", values, "idCardPic");
            return (Criteria) this;
        }

        public Criteria andIdCardPicNotIn(List<String> values) {
            addCriterion("id_card_pic not in", values, "idCardPic");
            return (Criteria) this;
        }

        public Criteria andIdCardPicBetween(String value1, String value2) {
            addCriterion("id_card_pic between", value1, value2, "idCardPic");
            return (Criteria) this;
        }

        public Criteria andIdCardPicNotBetween(String value1, String value2) {
            addCriterion("id_card_pic not between", value1, value2, "idCardPic");
            return (Criteria) this;
        }

        public Criteria andCareCardIsNull() {
            addCriterion("care_card is null");
            return (Criteria) this;
        }

        public Criteria andCareCardIsNotNull() {
            addCriterion("care_card is not null");
            return (Criteria) this;
        }

        public Criteria andCareCardEqualTo(String value) {
            addCriterion("care_card =", value, "careCard");
            return (Criteria) this;
        }

        public Criteria andCareCardNotEqualTo(String value) {
            addCriterion("care_card <>", value, "careCard");
            return (Criteria) this;
        }

        public Criteria andCareCardGreaterThan(String value) {
            addCriterion("care_card >", value, "careCard");
            return (Criteria) this;
        }

        public Criteria andCareCardGreaterThanOrEqualTo(String value) {
            addCriterion("care_card >=", value, "careCard");
            return (Criteria) this;
        }

        public Criteria andCareCardLessThan(String value) {
            addCriterion("care_card <", value, "careCard");
            return (Criteria) this;
        }

        public Criteria andCareCardLessThanOrEqualTo(String value) {
            addCriterion("care_card <=", value, "careCard");
            return (Criteria) this;
        }

        public Criteria andCareCardLike(String value) {
            addCriterion("care_card like", value, "careCard");
            return (Criteria) this;
        }

        public Criteria andCareCardNotLike(String value) {
            addCriterion("care_card not like", value, "careCard");
            return (Criteria) this;
        }

        public Criteria andCareCardIn(List<String> values) {
            addCriterion("care_card in", values, "careCard");
            return (Criteria) this;
        }

        public Criteria andCareCardNotIn(List<String> values) {
            addCriterion("care_card not in", values, "careCard");
            return (Criteria) this;
        }

        public Criteria andCareCardBetween(String value1, String value2) {
            addCriterion("care_card between", value1, value2, "careCard");
            return (Criteria) this;
        }

        public Criteria andCareCardNotBetween(String value1, String value2) {
            addCriterion("care_card not between", value1, value2, "careCard");
            return (Criteria) this;
        }

        public Criteria andCareCardPicIsNull() {
            addCriterion("care_card_pic is null");
            return (Criteria) this;
        }

        public Criteria andCareCardPicIsNotNull() {
            addCriterion("care_card_pic is not null");
            return (Criteria) this;
        }

        public Criteria andCareCardPicEqualTo(String value) {
            addCriterion("care_card_pic =", value, "careCardPic");
            return (Criteria) this;
        }

        public Criteria andCareCardPicNotEqualTo(String value) {
            addCriterion("care_card_pic <>", value, "careCardPic");
            return (Criteria) this;
        }

        public Criteria andCareCardPicGreaterThan(String value) {
            addCriterion("care_card_pic >", value, "careCardPic");
            return (Criteria) this;
        }

        public Criteria andCareCardPicGreaterThanOrEqualTo(String value) {
            addCriterion("care_card_pic >=", value, "careCardPic");
            return (Criteria) this;
        }

        public Criteria andCareCardPicLessThan(String value) {
            addCriterion("care_card_pic <", value, "careCardPic");
            return (Criteria) this;
        }

        public Criteria andCareCardPicLessThanOrEqualTo(String value) {
            addCriterion("care_card_pic <=", value, "careCardPic");
            return (Criteria) this;
        }

        public Criteria andCareCardPicLike(String value) {
            addCriterion("care_card_pic like", value, "careCardPic");
            return (Criteria) this;
        }

        public Criteria andCareCardPicNotLike(String value) {
            addCriterion("care_card_pic not like", value, "careCardPic");
            return (Criteria) this;
        }

        public Criteria andCareCardPicIn(List<String> values) {
            addCriterion("care_card_pic in", values, "careCardPic");
            return (Criteria) this;
        }

        public Criteria andCareCardPicNotIn(List<String> values) {
            addCriterion("care_card_pic not in", values, "careCardPic");
            return (Criteria) this;
        }

        public Criteria andCareCardPicBetween(String value1, String value2) {
            addCriterion("care_card_pic between", value1, value2, "careCardPic");
            return (Criteria) this;
        }

        public Criteria andCareCardPicNotBetween(String value1, String value2) {
            addCriterion("care_card_pic not between", value1, value2, "careCardPic");
            return (Criteria) this;
        }

        public Criteria andPrescriptionPicIsNull() {
            addCriterion("prescription_pic is null");
            return (Criteria) this;
        }

        public Criteria andPrescriptionPicIsNotNull() {
            addCriterion("prescription_pic is not null");
            return (Criteria) this;
        }

        public Criteria andPrescriptionPicEqualTo(String value) {
            addCriterion("prescription_pic =", value, "prescriptionPic");
            return (Criteria) this;
        }

        public Criteria andPrescriptionPicNotEqualTo(String value) {
            addCriterion("prescription_pic <>", value, "prescriptionPic");
            return (Criteria) this;
        }

        public Criteria andPrescriptionPicGreaterThan(String value) {
            addCriterion("prescription_pic >", value, "prescriptionPic");
            return (Criteria) this;
        }

        public Criteria andPrescriptionPicGreaterThanOrEqualTo(String value) {
            addCriterion("prescription_pic >=", value, "prescriptionPic");
            return (Criteria) this;
        }

        public Criteria andPrescriptionPicLessThan(String value) {
            addCriterion("prescription_pic <", value, "prescriptionPic");
            return (Criteria) this;
        }

        public Criteria andPrescriptionPicLessThanOrEqualTo(String value) {
            addCriterion("prescription_pic <=", value, "prescriptionPic");
            return (Criteria) this;
        }

        public Criteria andPrescriptionPicLike(String value) {
            addCriterion("prescription_pic like", value, "prescriptionPic");
            return (Criteria) this;
        }

        public Criteria andPrescriptionPicNotLike(String value) {
            addCriterion("prescription_pic not like", value, "prescriptionPic");
            return (Criteria) this;
        }

        public Criteria andPrescriptionPicIn(List<String> values) {
            addCriterion("prescription_pic in", values, "prescriptionPic");
            return (Criteria) this;
        }

        public Criteria andPrescriptionPicNotIn(List<String> values) {
            addCriterion("prescription_pic not in", values, "prescriptionPic");
            return (Criteria) this;
        }

        public Criteria andPrescriptionPicBetween(String value1, String value2) {
            addCriterion("prescription_pic between", value1, value2, "prescriptionPic");
            return (Criteria) this;
        }

        public Criteria andPrescriptionPicNotBetween(String value1, String value2) {
            addCriterion("prescription_pic not between", value1, value2, "prescriptionPic");
            return (Criteria) this;
        }

        public Criteria andTreatmentDateIsNull() {
            addCriterion("treatment_date is null");
            return (Criteria) this;
        }

        public Criteria andTreatmentDateIsNotNull() {
            addCriterion("treatment_date is not null");
            return (Criteria) this;
        }

        public Criteria andTreatmentDateEqualTo(String value) {
            addCriterion("treatment_date =", value, "treatmentDate");
            return (Criteria) this;
        }

        public Criteria andTreatmentDateNotEqualTo(String value) {
            addCriterion("treatment_date <>", value, "treatmentDate");
            return (Criteria) this;
        }

        public Criteria andTreatmentDateGreaterThan(String value) {
            addCriterion("treatment_date >", value, "treatmentDate");
            return (Criteria) this;
        }

        public Criteria andTreatmentDateGreaterThanOrEqualTo(String value) {
            addCriterion("treatment_date >=", value, "treatmentDate");
            return (Criteria) this;
        }

        public Criteria andTreatmentDateLessThan(String value) {
            addCriterion("treatment_date <", value, "treatmentDate");
            return (Criteria) this;
        }

        public Criteria andTreatmentDateLessThanOrEqualTo(String value) {
            addCriterion("treatment_date <=", value, "treatmentDate");
            return (Criteria) this;
        }

        public Criteria andTreatmentDateLike(String value) {
            addCriterion("treatment_date like", value, "treatmentDate");
            return (Criteria) this;
        }

        public Criteria andTreatmentDateNotLike(String value) {
            addCriterion("treatment_date not like", value, "treatmentDate");
            return (Criteria) this;
        }

        public Criteria andTreatmentDateIn(List<String> values) {
            addCriterion("treatment_date in", values, "treatmentDate");
            return (Criteria) this;
        }

        public Criteria andTreatmentDateNotIn(List<String> values) {
            addCriterion("treatment_date not in", values, "treatmentDate");
            return (Criteria) this;
        }

        public Criteria andTreatmentDateBetween(String value1, String value2) {
            addCriterion("treatment_date between", value1, value2, "treatmentDate");
            return (Criteria) this;
        }

        public Criteria andTreatmentDateNotBetween(String value1, String value2) {
            addCriterion("treatment_date not between", value1, value2, "treatmentDate");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNull() {
            addCriterion("admin_id is null");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNotNull() {
            addCriterion("admin_id is not null");
            return (Criteria) this;
        }

        public Criteria andAdminIdEqualTo(Long value) {
            addCriterion("admin_id =", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotEqualTo(Long value) {
            addCriterion("admin_id <>", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThan(Long value) {
            addCriterion("admin_id >", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThanOrEqualTo(Long value) {
            addCriterion("admin_id >=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThan(Long value) {
            addCriterion("admin_id <", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThanOrEqualTo(Long value) {
            addCriterion("admin_id <=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdIn(List<Long> values) {
            addCriterion("admin_id in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotIn(List<Long> values) {
            addCriterion("admin_id not in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdBetween(Long value1, Long value2) {
            addCriterion("admin_id between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotBetween(Long value1, Long value2) {
            addCriterion("admin_id not between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Long value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Long value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Long value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Long value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Long value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Long> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Long> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Long value1, Long value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Long value1, Long value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andInvoicePicIsNull() {
            addCriterion("invoice_pic is null");
            return (Criteria) this;
        }

        public Criteria andInvoicePicIsNotNull() {
            addCriterion("invoice_pic is not null");
            return (Criteria) this;
        }

        public Criteria andInvoicePicEqualTo(String value) {
            addCriterion("invoice_pic =", value, "invoicePic");
            return (Criteria) this;
        }

        public Criteria andInvoicePicNotEqualTo(String value) {
            addCriterion("invoice_pic <>", value, "invoicePic");
            return (Criteria) this;
        }

        public Criteria andInvoicePicGreaterThan(String value) {
            addCriterion("invoice_pic >", value, "invoicePic");
            return (Criteria) this;
        }

        public Criteria andInvoicePicGreaterThanOrEqualTo(String value) {
            addCriterion("invoice_pic >=", value, "invoicePic");
            return (Criteria) this;
        }

        public Criteria andInvoicePicLessThan(String value) {
            addCriterion("invoice_pic <", value, "invoicePic");
            return (Criteria) this;
        }

        public Criteria andInvoicePicLessThanOrEqualTo(String value) {
            addCriterion("invoice_pic <=", value, "invoicePic");
            return (Criteria) this;
        }

        public Criteria andInvoicePicLike(String value) {
            addCriterion("invoice_pic like", value, "invoicePic");
            return (Criteria) this;
        }

        public Criteria andInvoicePicNotLike(String value) {
            addCriterion("invoice_pic not like", value, "invoicePic");
            return (Criteria) this;
        }

        public Criteria andInvoicePicIn(List<String> values) {
            addCriterion("invoice_pic in", values, "invoicePic");
            return (Criteria) this;
        }

        public Criteria andInvoicePicNotIn(List<String> values) {
            addCriterion("invoice_pic not in", values, "invoicePic");
            return (Criteria) this;
        }

        public Criteria andInvoicePicBetween(String value1, String value2) {
            addCriterion("invoice_pic between", value1, value2, "invoicePic");
            return (Criteria) this;
        }

        public Criteria andInvoicePicNotBetween(String value1, String value2) {
            addCriterion("invoice_pic not between", value1, value2, "invoicePic");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table apply
     *
     * @mbg.generated do_not_delete_during_merge Sat May 02 11:25:55 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table apply
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}