package gov.shenyang.zwfw.model;

public class TreatmentRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatment_record.id
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatment_record.user_id
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatment_record.hospital
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    private String hospital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatment_record.treatment_date
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    private String treatmentDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatment_record.gmt_create
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatment_record.gmt_modified
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatment_record.state
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatment_record.id
     *
     * @return the value of treatment_record.id
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatment_record.id
     *
     * @param id the value for treatment_record.id
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatment_record.user_id
     *
     * @return the value of treatment_record.user_id
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatment_record.user_id
     *
     * @param userId the value for treatment_record.user_id
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatment_record.hospital
     *
     * @return the value of treatment_record.hospital
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatment_record.hospital
     *
     * @param hospital the value for treatment_record.hospital
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public void setHospital(String hospital) {
        this.hospital = hospital == null ? null : hospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatment_record.treatment_date
     *
     * @return the value of treatment_record.treatment_date
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public String getTreatmentDate() {
        return treatmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatment_record.treatment_date
     *
     * @param treatmentDate the value for treatment_record.treatment_date
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public void setTreatmentDate(String treatmentDate) {
        this.treatmentDate = treatmentDate == null ? null : treatmentDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatment_record.gmt_create
     *
     * @return the value of treatment_record.gmt_create
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatment_record.gmt_create
     *
     * @param gmtCreate the value for treatment_record.gmt_create
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatment_record.gmt_modified
     *
     * @return the value of treatment_record.gmt_modified
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatment_record.gmt_modified
     *
     * @param gmtModified the value for treatment_record.gmt_modified
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatment_record.state
     *
     * @return the value of treatment_record.state
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatment_record.state
     *
     * @param state the value for treatment_record.state
     *
     * @mbg.generated Sat May 02 11:25:55 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}